- name: modify apt-key
  apt_key: 
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"

- name: modify repository
  apt_repository:
    repo: "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main"
    state: present

- name: install elasticsearch
  apt:
    name: "elasticsearch={{ es_version }}*"
    state: present
    force: yes

- name: install plugins
  shell: "/usr/share/elasticsearch/bin/plugin install {{ item.name }}/{{ item.version | default('') }}"
  args:
    creates: "/usr/share/elasticsearch/plugins/{{ item.name.split('elasticsearch-')[-1] }}"
  with_items: es_plugins

- name: modify sysconfig
  template:
    src: sysconfig
    dest: /etc/default/elasticsearch
    owner: root
    group: root
    mode: 0644

- name: modify elasticsearch.yml
  template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: root
    mode: 0644

- name: modify logging.yml
  template:
    src: logging.yml
    dest: /etc/elasticsearch/logging.yml
    owner: root
    group: root
    mode: 0644

- name: modify template directory
  file:
    path: /etc/elasticsearch/templates
    state: directory
    owner: root
    group: root
    mode: 0755

- name: elasticsearch is enabled
  service:
    name: elasticsearch
    enabled: yes
