# file: roles/elasticsearch/tasks/plugin_aws.yml

- name: modify sysconfig
  lineinfile:
    dest: /etc/default/elasticsearch
    line: '{{ item }}'
    state: present
    insertafter: EOF
  with_items:
    - '# Amazon EC2 Tag'
    - 'INSTANCE_ID=$(/usr/bin/curl -s http://169.254.169.254/latest/meta-data/instance-id)'
    - 'export TAG_SERVICE=$(/opt/aws/bin/ec2-describe-tags --region ap-northeast-1 --filter "resource-id=${INSTANCE_ID}" --filter "key=service" |cut -f5)'
    - 'export TAG_ROLE=$(/opt/aws/bin/ec2-describe-tags --region ap-northeast-1 --filter "resource-id=${INSTANCE_ID}" --filter "key=role" |cut -f5)'


- name: install elasticsearch-cloud-aws 2.5.1
  shell: "/usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-cloud-aws/2.5.1"
  args:
    creates: "/usr/share/elasticsearch/plugins/cloud-aws"
  when: "{{ version[:3] }} | version_compare('1.5', '==')"

- name: install elasticsearch-cloud-aws 2.6.1
  shell: "/usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-cloud-aws/2.6.1"
  args:
    creates: "/usr/share/elasticsearch/plugins/cloud-aws"
  when: "{{ version[:3] }} | version_compare('1.6', '==')"

- name: install elasticsearch-cloud-aws 2.7.1
  shell: "/usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-cloud-aws/2.7.1"
  args:
    creates: "/usr/share/elasticsearch/plugins/cloud-aws"
  when: "{{ version[:3] }} | version_compare('1.7', '==')"
