# file: roles/elasticsearch/tasks/plugin_analysis_icu.yml

- name: install elasticsearch-analysis-icu 2.5.0
  sudo: yes
  shell: "/usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.5.0"
  args:
    creates: "/usr/share/elasticsearch/plugins/analysis-icu"
  when: "{{ version[:3] }} | version_compare('1.5', '==')"

- name: install elasticsearch-analysis-icu 2.6.0
  sudo: yes
  shell: "/usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.6.0"
  args:
    creates: "/usr/share/elasticsearch/plugins/analysis-icu"
  when: "{{ version[:3] }} | version_compare('1.6', '==')"

- name: install elasticsearch-analysis-icu 2.7.0
  sudo: yes
  shell: "/usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-analysis-icu/2.7.0"
  args:
    creates: "/usr/share/elasticsearch/plugins/analysis-icu"
  when: "{{ version[:3] }} | version_compare('1.7', '==')"
